# A Heat environment file which can be used to enable a
# a Neutron Nuage backend on the controller, configured via puppet
resource_registry:
  OS::TripleO::ControllerExtraConfigPre: ../puppet/extraconfig/pre_deploy/controller/neutron-nuage.yaml

parameter_defaults:
  NeutronNuageOSControllerIp: '0.0.0.0'
  NeutronNuageNetPartitionName: 'default_name'
  NeutronNuageVSDIp: '0.0.0.0:0'
  NeutronNuageVSDUsername: 'username'
  NeutronNuageVSDPassword: 'password'
  NeutronNuageVSDOrganization: 'organization'
  NeutronNuageBaseURIVersion: 'default_uri_version'
  NeutronNuageCMSId: ''
  NeutronNuageFIPUnderlay: true
  NeutronNuagePAT: 'default_enabled'
  UseForwardedFor: true
