# A Heat environment file which can be used to enable a
# a Nuage backend on the compute, configured via puppet
resource_registry:
  OS::TripleO::ComputeExtraConfigPre: ../puppet/extraconfig/pre_deploy/compute/nova-nuage.yaml

parameter_defaults:
  NuageActiveController: '0.0.0.0'
  NuageStandbyController: '0.0.0.0'
  #Interface name on Compute that is on External network (default: br-ex)
  NuageNetworkUplinkIntf: 'br-ex'
